### ISSUE TITLE
Role problems

### ISSUE THREAD

**Issue by TimeLost4** [TTT-2/ttt2-role_unk#3]
The unknown did not spawn when killed. It happend when teh amnesiac killed the unknown and the unknown did not respawn so are there roles that the unknown can not "take". (sry for bad english etc.)

**Comment by TimGoll** [comment]
The unknown does only respawn if he is killed with a weapon that has a killer
E.g. the friendship bean does not have a killer and the player is killed by world. Are you sure that the unknown was killed with a correctly coded weapon? Please give some more information to reproduce.

(If you're german, you can write in german as well)

**Comment by TimeLost4** [comment]
Ja okay danke ^^ also ich wurde mit der G3SG1 getötet (headshot) vom amnesiac

**Comment by TimGoll** [comment]
Ah, der Amnesiac hat auch kein Team. Kann sein, dass er das daher nicht annimmt. Bin mir nicht ganz sicher.

**Comment by TimeLost4** [comment]
okay danke das könnte natürlich sein. Noch eine frage bei uns vertragen sich Detective, Sniffer und Sheriff nicht sie spawnen nicht wenn alle an sind. Gibt es da bekannte Probleme?

**Comment by TimeLost4** [comment]
Als der Unknown vom Hitman getötet wurde ist dieser auch nicht wiederbelebt worden. Dieser müsste ja ein Team haben die Traitor. Möglich wäre das der Unknown nur von Den Rollen getötet werden kann, um zu respawnen, die direkt in dem Team sind. Also halt traitor aber nicht Vampir und Hitman nicht.

**Comment by TimGoll** [comment]
nene, das defintiv nicht. Das letzte Mal, als ich das gecheckt hatte, ist der unknown auch noch respawned.

Zwei Dinge müssen erfüllt sein:
- Die Waffe muss den Killer korrekt registrieren
- Der Killer muss noch leben, wenn der Unknown wiederbelebt wird

**Comment by TimeLost4** [comment]
okay vielen dank. dann lag es daran... beide male sind die Killer vorher gestorben. Okay nochmal vielen Dank ^^

**Comment by TimGoll** [comment]
alles klar! Wir werden wohl da noch ein paar mehr Infos zu revivals ingame hinzufügen, damit die Leute Bescheid wissen

**Comment by Alf21** [comment]
Und die eigene Leiche muss glaube noch existieren (kann durch Brennen verschwinden).
