### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_unk#4]
With the last commits, the unknown no longer works and not respawn
also i get this error in server side console 
![image](https://user-images.githubusercontent.com/36534723/80813688-cb60e100-8bca-11ea-8b03-a2daf805b696.png)
I tried every role and the unknown didn't respawn

**Comment by TimGoll** [comment]
Hm, please use an older commit. This might be caused by some not yet merged PRs on GitHub. Sorry.

**Comment by ThePlatinumGhost** [comment]
Ok, i tested and with this commits b1cd37232b150c4ab8019c39218b9d932f4b1b2e
works fine, i thinks i will stick with this commit for now

**Comment by ThePlatinumGhost** [comment]
Fixed with 76a7e648108115a09f755be28c7fa5f118a5fe65
