### ISSUE TITLE
Rebirth is canceled for the living.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_unk#6]
![отмена](https://user-images.githubusercontent.com/7480655/83742170-c677cd00-a661-11ea-82d1-23659fc42de9.png)
I was unknown, I was killed a long time ago, I became innocent, but for some reason I was written at some point that my killer died and my rebirth is canceled, this is not the first time I see this.

**Comment by TimGoll** [comment]
Ahh, thanks! I probably forgot to clear a state somewhere

**Comment by TimGoll** [comment]
I think I fixed it, but I couldn't test it all by myself. Please report back if there are any problems.
